Repository Coffect/coffect-FE, pull requests merged in 2025-07, with the labels that each got.

#51 [Refactor] Commnet 부분 리팩토링
  coffect/src/api/commentApi.ts
  coffect/src/components/communityComponents/comment/CommentInput.tsx
  coffect/src/components/communityComponents/comment/CommentItem.tsx
  coffect/src/components/communityComponents/comment/CommentList.tsx
  coffect/src/hooks/useComments.ts
  coffect/src/hooks/usePostDetail.ts
  coffect/src/types/commentTypes.ts
Labels: ♻️Refactor

#39 [ Chore ] 프로젝트 세팅: 절대 경로 추가
  coffect/src/App.tsx
  coffect/src/pages/Community.tsx
  coffect/tsconfig.app.json
  coffect/vite.config.ts
Labels: 📌Chore

#60 [Fix] 피드 상세페이지에서 댓글 버튼 클릭 시 리렌더링이 반복되는 버그 수정
  coffect/src/App.tsx
  coffect/src/assets/icon/Signup/Start.png
  coffect/src/assets/icon/Signup/checkbox.png
  coffect/src/assets/icon/Signup/clickCheckbox.png
  coffect/src/assets/icon/home/CardLeft.png
  coffect/src/assets/icon/home/CardMid.png
  coffect/src/assets/icon/home/CardRight.png
  coffect/src/assets/icon/home/Logo.png
  coffect/src/assets/icon/home/NoAlarm.png
  coffect/src/assets/icon/home/NoCalendar.png
  coffect/src/assets/icon/home/NoCard.png
  coffect/src/assets/icon/home/NoSuggest.png
  coffect/src/assets/icon/home/Profile.png
  coffect/src/assets/icon/home/SuggestResponse.png
  coffect/src/components/Home/AlarmView.tsx
  coffect/src/components/Home/CalenderView.tsx
  coffect/src/components/Home/CardDetailView.tsx
  coffect/src/components/Home/CoffeeCategoryGrid.tsx
  coffect/src/components/Home/CoffeeSuggestBanner.tsx
  coffect/src/components/Home/CoffeeSuggestCompleteModal.tsx
  coffect/src/components/Home/CoffeeSuggestModal.tsx
  coffect/src/components/Home/CoffeeSuggestResponseModal.tsx
  coffect/src/components/Home/NoAlarm.tsx
  coffect/src/components/Home/NoSchedule.tsx
  coffect/src/components/Home/ProfileFlip.tsx
  coffect/src/components/Home/ProfileModal.tsx
  coffect/src/components/Home/TopNavbar.tsx
  coffect/src/components/Signup/AccountSetup.tsx
  coffect/src/components/Signup/CodeInput.tsx
  coffect/src/components/Signup/Completion.tsx
  coffect/src/components/Signup/EmailVerification.tsx
  coffect/src/components/Signup/InterestsSelection.tsx
  coffect/src/components/Signup/LoginChoice.tsx
  coffect/src/components/Signup/ProfileSetup.tsx
  coffect/src/components/Signup/SchoolSelection.tsx
  coffect/src/components/Signup/SplashScreen.tsx
  coffect/src/components/Signup/TermsAgreement.tsx
  coffect/src/components/Signup/TermsDetail.tsx
  coffect/src/components/UserPage/MyPage/BookMark.tsx
  coffect/src/components/UserPage/MyPage/MyProfile/MyProfile.tsx
  coffect/src/components/UserPage/OtherUserPage/UserProfile.tsx
  coffect/src/components/communityComponents/feed/FeedInteraction.tsx
  coffect/src/components/communityComponents/feed/FeedList.tsx
  coffect/src/components/shareComponents/FeedItem.tsx
  coffect/src/components/shareComponents/post/PostAuthorInfo.tsx
  coffect/src/components/shareComponents/post/PostBody.tsx
  coffect/src/hooks/community/useClampManager.ts
  coffect/src/hooks/community/useCommunityData.ts
  coffect/src/pages/Community.tsx
  coffect/src/pages/Home.tsx
  coffect/src/pages/Login.tsx
  coffect/src/pages/Signup.tsx
  coffect/src/routes/homePageRoutes.tsx
Labels: 🐛Fix

#66 [Refactor] WritePost (글 작성 페이지) 부부 리팩토링
  coffect/src/api/postApi.ts
  coffect/src/components/communityComponents/ChipFilterComponent/ChipGroup.tsx
  coffect/src/components/communityComponents/writeComponents/SuccessModal/UploadSuccessModal.tsx
  coffect/src/components/communityComponents/writeComponents/WritePost.tsx
  coffect/src/components/communityComponents/writeComponents/WritePostContentInput.tsx
  coffect/src/components/communityComponents/writeComponents/WritePostHeader.tsx
  coffect/src/components/communityComponents/writeComponents/WritePostTitleInput.tsx
  coffect/src/components/communityComponents/writeComponents/WritePostTopicSelector.tsx
  coffect/src/components/communityComponents/writeComponents/WritePostUI.tsx
  coffect/src/hooks/useWritePost.ts
  coffect/src/pages/Community.tsx
  coffect/src/routes/CommunityRoutes.tsx
  coffect/src/types/writePostTypes.ts
Labels: ♻️Refactor

#68 [Feat] 회원 가입 페이지 온보딩 추가
  coffect/src/assets/icon/Signup/onboardingLogo.png
  coffect/src/assets/icon/Signup/slide1.png
  coffect/src/assets/icon/Signup/slide2.png
  coffect/src/assets/icon/Signup/slide3.png
  coffect/src/assets/icon/Signup/slide4.png
  coffect/src/components/Signup/OnboardingLayout.tsx
  coffect/src/components/Signup/OnboardingPage.tsx
  coffect/src/components/Signup/OnboardingSlide.tsx
  coffect/src/pages/Signup.tsx
  coffect/src/routes/signupRoutes.tsx
Labels: ✨Feature

#70 [Feat] 온보딩 구현 및 회원가입 API 일부 연동, 레이아웃 리팩토링 통합
  coffect/package.json
  coffect/src/api/auth.ts
  coffect/src/api/axiosInstance.ts
  coffect/src/api/univ.ts
  coffect/src/assets/icon/Signup/onboardingLogo.png
  coffect/src/assets/icon/Signup/slide1.png
  coffect/src/assets/icon/Signup/slide2.png
  coffect/src/assets/icon/Signup/slide3.png
  coffect/src/assets/icon/Signup/slide4.png
  coffect/src/components/Signup/AccountSetup.tsx
  coffect/src/components/Signup/CodeInput.tsx
  coffect/src/components/Signup/Completion.tsx
  coffect/src/components/Signup/EmailVerification.tsx
  coffect/src/components/Signup/InterestsSelection.tsx
  coffect/src/components/Signup/LoginChoice.tsx
  coffect/src/components/Signup/OnboardingLayout.tsx
  coffect/src/components/Signup/OnboardingPage.tsx
  coffect/src/components/Signup/OnboardingSlide.tsx
  coffect/src/components/Signup/ProfileSetup.tsx
  coffect/src/components/Signup/SchoolSelection.tsx
  coffect/src/components/Signup/SplashScreen.tsx
  coffect/src/components/Signup/TermsAgreement.tsx
  coffect/src/components/Signup/TermsDetail.tsx
  coffect/src/components/Signup/TopNavbar.tsx
  coffect/src/components/Signup/shared/SignupLayout.tsx
  coffect/src/constants/key.ts
  coffect/src/pages/Signup.tsx
  coffect/src/routes/signupRoutes.tsx
  coffect/src/types/signup.ts
Labels: ✨Feature
