Repository Coffect/coffect-FE, pull requests merged in 2025-08, with the labels that each got.

#90 [Feat] 게시글 상세 페이지 구현 및 API 연결
  coffect/src/api/community/postApi.ts
  coffect/src/components/communityComponents/comment/CommentInput.tsx
  coffect/src/components/communityComponents/feed/FeedInteraction.tsx
  coffect/src/components/communityComponents/feed/FeedList.tsx
  coffect/src/hooks/usePostDetail.ts
  coffect/src/pages/PostDetail.tsx
  coffect/src/pages/PostDetailPage.tsx
  coffect/src/routes/CommunityRoutes.tsx
  coffect/src/types/community/postTypes.ts
  coffect/src/utils/dateUtils.ts
Labels: ✨Feature, ♻️Refactor

#92 [Refactor] 게시물 불러오기 react-query 를 활용하도록 리팩토링
  coffect/src/components/UserPage/MyPage/ChatRecord/ChatCard.tsx
  coffect/src/components/UserPage/MyPage/LeaveModal.tsx
  coffect/src/components/UserPage/MyPage/MyProfile/DetailIntro.tsx
  coffect/src/components/UserPage/MyPage/MyProfile/MyProfile.tsx
  coffect/src/components/UserPage/MyPage/TimeTable.tsx
  coffect/src/pages/Community.tsx
  coffect/src/pages/MyPage.tsx
Labels: ♻️Refactor

#94 [Refactor] Comment 훅 분리 및 useQuery의 select 옵션 활용
  coffect/src/api/community/commentApi.ts
  coffect/src/api/community/postApi.ts
  coffect/src/components/communityComponents/comment/CommentInput.tsx
  coffect/src/hooks/community/query/usePostDetail.ts
  coffect/src/hooks/useComments.ts
  coffect/src/hooks/usePostDetail.ts
  coffect/src/pages/PostDetailPage.tsx
Labels: ♻️Refactor

#105 [Feat] 홈 페이지 PM님 2차 QA 반영
  coffect/package.json
  coffect/pnpm-lock.yaml
  coffect/src/assets/icon/home/CardRightDown.png
  coffect/src/assets/icon/home/CardRightUp.png
  coffect/src/assets/icon/home/choose1.png
  coffect/src/assets/icon/home/choose2.png
  coffect/src/assets/icon/home/choose3.png
  coffect/src/assets/icon/home/choose4.png
  coffect/src/assets/icon/home/errorToast.png
  coffect/src/assets/icon/home/successToast.png
  coffect/src/components/Home/CardsView.tsx
  coffect/src/components/Home/CoffeeCategoryGrid.tsx
  coffect/src/components/Home/CoffeeSuggestBanner.tsx
  coffect/src/components/Home/MessageModal.tsx
  coffect/src/components/Home/ProfileFlip.tsx
  coffect/src/components/Home/Toast.tsx
  coffect/src/components/UserPage/MyPage/ChatRecord/ChatCard.tsx
  coffect/src/components/UserPage/MyPage/LeaveModal.tsx
  coffect/src/components/UserPage/MyPage/MyProfile/DetailIntro.tsx
  coffect/src/components/UserPage/MyPage/MyProfile/MyProfile.tsx
  coffect/src/components/UserPage/MyPage/TimeTable.tsx
  coffect/src/hooks/useToastStore.ts
  coffect/src/pages/MyPage.tsx
Labels: ✨Feature

#109 [Refactor] 댓글 추가 기능 관련 API 타입 재정의 및 mutation 수정
  coffect/src/api/community/commentApi.ts
  coffect/src/api/postApi.ts
  coffect/src/components/communityComponents/comment/CommentInput.tsx
  coffect/src/hooks/community/mutation/useAddComment.ts
  coffect/src/hooks/community/useCommunityData.ts
  coffect/src/hooks/community/useCommunityFeed.ts
  coffect/src/pages/Community.tsx
  coffect/src/types/community/commentTypes.ts
Labels: ♻️Refactor, ❌ Remove

#81 [Feat] 회원 가입 페이지 API 연동(이메일 인증, 회원가입 정보 전달 api) + 2차 QA 반영
  coffect/package.json
  coffect/pnpm-lock.yaml
  coffect/src/api/auth.ts
  coffect/src/api/axiosMail.ts
  coffect/src/api/univ.ts
  coffect/src/assets/icon/Signup/DefaultAvatar.png
  coffect/src/assets/icon/Signup/SignupEnd.png
  coffect/src/assets/icon/Signup/Start.png
  coffect/src/assets/icon/Signup/checkbox.png
  coffect/src/assets/icon/Signup/clickCheckbox.png
  coffect/src/assets/icon/Signup/onboardingLogo.png
  coffect/src/assets/icon/Signup/slide1.png
  coffect/src/assets/icon/Signup/slide2.png
  coffect/src/assets/icon/Signup/slide3.png
  coffect/src/assets/icon/Signup/slide4.png
  coffect/src/assets/icon/home/Logo.png
  coffect/src/assets/icon/home/errorToast.png
  coffect/src/assets/icon/home/successToast.png
  coffect/src/assets/icon/signup/DefaultAvatar.png
  coffect/src/assets/icon/signup/defaultAvatar.png
  coffect/src/assets/icon/signup/profilePencil.png
  coffect/src/components/Home/Toast.tsx
  coffect/src/components/Signup/AccountSetup.tsx
  coffect/src/components/Signup/AgreementItem.tsx
  coffect/src/components/Signup/CodeInput.tsx
  coffect/src/components/Signup/Completion.tsx
  coffect/src/components/Signup/EmailVerification.tsx
  coffect/src/components/Signup/InterestsSelection.tsx
  coffect/src/components/Signup/LoginChoice.tsx
  coffect/src/components/Signup/ProfileSetup.tsx
  coffect/src/components/Signup/SchoolSelection.tsx
  coffect/src/components/Signup/SplashScreen.tsx
  coffect/src/components/Signup/TermsAgreement.tsx
  coffect/src/components/Signup/shared/SignupLayout.tsx
  coffect/src/hooks/useDebounce.ts
  coffect/src/hooks/useToastStore.ts
  coffect/src/pages/Signup.tsx
  coffect/src/types/signup.ts
  coffect/src/utils/validation.ts
Labels: ✨Feature

#124 [Feat] 추천 카드에 전공·QnA정보 및 팔로우 상태 API 추가
  coffect/.gitignore
  coffect/.husky/_/pre-commit
  coffect/.husky/pre-commit
  coffect/.npmrc
  coffect/eslint.config.js
  coffect/index.html
  coffect/package.json
  coffect/pnpm-lock.yaml
  coffect/prettier.config.cjs
  coffect/src/api/commentApi.ts
  coffect/src/api/home.ts
  coffect/src/components/Home/ProfileFlip.tsx
  coffect/src/components/Signup/Completion.tsx
  coffect/src/components/Signup/ProfileSetup.tsx
  coffect/src/components/communityComponents/writeComponents/WritePost.tsx
  coffect/src/main.tsx
  coffect/src/types/home.ts
  coffect/tmp.txt
Labels: ✨Feature

#131 [Feat] API 연동
  coffect/src/api/community/commentApi.ts
  coffect/src/api/community/postApi.ts
  coffect/src/api/community/writeApi.ts
  coffect/src/components/UserPage/MyPage/BookMark.tsx
  coffect/src/components/UserPage/MyPage/MyProfile/MyProfile.tsx
  coffect/src/components/UserPage/OtherUserPage/UserProfile.tsx
  coffect/src/components/communityComponents/BottomSeatFilter/FilterModal.tsx
  coffect/src/components/communityComponents/ChipFilterComponent/ChipGroup.tsx
  coffect/src/components/communityComponents/ChipFilterComponent/filterData.ts
  coffect/src/components/communityComponents/comment/CommentInput.tsx
  coffect/src/components/communityComponents/comment/CommentList.tsx
  coffect/src/components/communityComponents/feed/FeedInteraction.tsx
  coffect/src/components/communityComponents/writeComponents/WritePostContentInput.tsx
  coffect/src/components/communityComponents/writeComponents/WritePostTitleInput.tsx
  coffect/src/components/communityComponents/writeComponents/WritePostTopicSelector.tsx
  coffect/src/components/postDetailComponents/PostDetailComments.tsx
  coffect/src/components/shareComponents/post/PostBody.tsx
  coffect/src/components/shareComponents/post/PostContent.tsx
  coffect/src/components/shareComponents/post/PostTags.tsx
  coffect/src/constants/key.ts
  coffect/src/hooks/community/mutation/useAddComment.ts
  coffect/src/hooks/community/mutation/useAddPost.ts
  coffect/src/hooks/community/mutation/useAddPostMutation.ts
  coffect/src/hooks/community/mutation/useUploadPostImageMutation.ts
  coffect/src/hooks/community/mutation/useUploadPostMutation.ts
  coffect/src/hooks/community/query/useGetComments.ts
  coffect/src/hooks/community/query/useGetCommunityPostsQuery.ts
  coffect/src/hooks/community/query/usePostDetail.ts
  coffect/src/hooks/community/useCommunityHeaderFilters.ts
  coffect/src/hooks/community/writePost/usePostCreation.ts
  coffect/src/hooks/community/writePost/useWritePost.ts
  coffect/src/hooks/community/writePost/useWritePostForm.ts
  coffect/src/pages/Community.tsx
  coffect/src/pages/PostDetailPage.tsx
  coffect/src/pages/WritePostPage.tsx
  coffect/src/store/community/communityStore.ts
  coffect/src/types/community/commentTypes.ts
  coffect/src/types/community/postTypes.ts
  coffect/src/types/community/writePostTypes.ts
Labels: ✨Feature, ♻️Refactor, ❌ Remove, 📌Chore

#139 [Feat] 학교 도메인 검증 API 설정 및 연결
  coffect/src/api/univ.ts
  coffect/src/components/Signup/EmailVerification.tsx
  coffect/src/utils/validation.ts
Labels: ✨Feature

#141 Feature/mypage 122
  coffect/src/api/profile.ts
  coffect/src/components/UserPage/MyPage/TimeTable.tsx
  coffect/src/components/UserPage/Profile/UserProfile.tsx
  coffect/src/pages/MyPage.tsx
  coffect/src/types/mypage/profile.ts
Labels: ✨Feature

#158 [Feat] 홈페이지 제안 모달 채팅 api 연결
  coffect/src/components/Home/CoffeeSuggestBanner.tsx
Labels: ✨Feature

#172 [Feat] ios 에서 알림 권한 요청 추가
  coffect/src/components/Home/PushEnableButton.tsx
  coffect/src/pages/Home.tsx
Labels: ✨Feature

#173 [Fix] 회원가입 페이지 protected 라우터 설정 및 세부 ui 수정
  coffect/src/App.tsx
  coffect/src/components/Signup/CodeInput.tsx
  coffect/src/components/Signup/ProtectedRoute.tsx
  coffect/src/components/Signup/TermsDetail.tsx
Labels: 🐛Fix

#186 [Feat] 낙관적 업데이트가 안되는 버그 수정
  coffect/src/components/communityComponents/comment/CommentInput.tsx
  coffect/src/constants/key.ts
  coffect/src/constants/queryKey.ts
  coffect/src/hooks/community/mutation/useAddComment.ts
  coffect/src/hooks/community/mutation/useAddCommentMutation.ts
  coffect/src/hooks/community/mutation/useFollowMutation.ts
  coffect/src/hooks/community/mutation/useLikePostMutation.ts
  coffect/src/hooks/community/mutation/useScrapPostMutation.ts
  coffect/src/hooks/community/mutation/useThreadInteractionMutation.ts
  coffect/src/hooks/community/query/useGetComments.ts
  coffect/src/hooks/community/query/useGetCommunityPostsQuery.ts
  coffect/src/hooks/community/query/useGetThreadLatestQuery.ts
  coffect/src/hooks/community/query/usePostDetail.ts
  coffect/src/pages/Community.tsx
  coffect/src/types/community/commentTypes.ts
Labels: ♻️Refactor, 🐛Fix

#196 [Feat] 팔로우/팔로워 기능 및 UI 추가
  coffect/src/api/follow.ts
  coffect/src/components/Signup/AccountSetup.tsx
  coffect/src/components/Signup/ProfileSetup.tsx
  coffect/src/components/UserPage/Profile/UserProfile.tsx
  coffect/src/components/communityComponents/feed/FeedList.tsx
  coffect/src/components/follow/FollowItem.tsx
  coffect/src/components/follow/FollowList.tsx
  coffect/src/components/follow/followHeader.tsx
  coffect/src/components/follow/skeleton/FollowItemSkeleton.tsx
  coffect/src/components/follow/skeleton/FollowingListSkeleton.tsx
  coffect/src/constants/queryKey.ts
  coffect/src/hooks/follow/query.ts
  coffect/src/pages/FolloingPage.tsx
  coffect/src/pages/FollowerPage.tsx
  coffect/src/pages/MyPage.tsx
  coffect/src/routes/userPageRoutes.tsx
  coffect/src/types/follow/countFollow.ts
  coffect/src/types/follow/listUpFollow.ts
  coffect/src/utils/validation.ts
Labels: ✨Feature, 🎨Design

#203 [Feat] 웹앱 환경 설정 및 배너 오류 수정
  coffect/index.html
  coffect/public/icons/pwa-192.png
  coffect/public/icons/pwa-522.png
  coffect/src/components/Home/CoffeeSuggestBanner.tsx
  coffect/src/sw.ts
  coffect/vite.config.ts
Labels: ✨Feature, 🐛Fix

#205 [Feat] 회원가입 페이지 학교-이메일 도메인 일치 여부 추가
  coffect/src/api/univ.ts
  coffect/src/components/Signup/EmailVerification.tsx
  coffect/src/pages/Signup.tsx
Labels: ✨Feature

#208 [Feat] 디자인 부분 수정 및 기능 개선
  coffect/src/assets/icon/community/bookmark.svg
  coffect/src/assets/icon/community/commentImage.png
  coffect/src/assets/icon/community/defaultImage.png
  coffect/src/assets/icon/community/heart.svg
  coffect/src/assets/icon/shareComponents/followZero.png
  coffect/src/components/communityComponents/comment/CommentInput.tsx
  coffect/src/components/communityComponents/comment/CommentItem.tsx
  coffect/src/components/communityComponents/feed/FeedInteraction.tsx
  coffect/src/components/communityComponents/feed/FeedList.tsx
  coffect/src/components/communityComponents/writeComponents/WritePostContentInput.tsx
  coffect/src/components/follow/FollowItem.tsx
  coffect/src/components/follow/followHeader.tsx
  coffect/src/components/postDetailComponents/PostDetailComments.tsx
  coffect/src/components/shareComponents/FeedItem.tsx
  coffect/src/components/shareComponents/imageCrop/ImageCropModal.tsx
  coffect/src/hooks/community/mutation/useAddCommentMutation.ts
  coffect/src/hooks/community/mutation/useAddPostMutation.ts
  coffect/src/pages/Community.tsx
  coffect/src/pages/FolloingPage.tsx
  coffect/src/pages/FollowerPage.tsx
  coffect/src/pages/PostDetailPage.tsx
  coffect/src/pages/WritePostPage.tsx
Labels: ✨Feature, ♻️Refactor, 🎨Design, 🐛Fix

#210 fix: 글 작성 이미지 크기 조절 로직 수정
  coffect/index.html
  coffect/src/assets/icon/community/imageCut.png
  coffect/src/components/communityComponents/writeComponents/WritePostContentInput.tsx
  coffect/src/components/shareComponents/imageCrop/ImageCropModal.tsx
  coffect/src/pages/WritePostPage.tsx
Labels: ✨Feature, ♻️Refactor, 🎨Design

#213 [Fix]manifest 사용 후 FCM 수신 오류 문제 해결
  coffect/index.html
  coffect/public/icons/pwa-512.png
  coffect/public/icons/pwa-522.png
  coffect/src/components/Home/PushEnableButton.tsx
  coffect/src/sw.ts
  coffect/vite.config.ts
Labels: 🐛Fix

#221 [Fix] 댓글 2줄 이상 작성 시에 이미지 깨지는 문제 수정
  coffect/src/components/communityComponents/comment/CommentItem.tsx
Labels: 🎨Design, 🐛Fix

#229 [Chore] 홈페이지 디자인 최종 수정
  coffect/src/api/home.ts
  coffect/src/components/Home/CalenderView.tsx
  coffect/src/components/Home/CardDetailView.tsx
  coffect/src/components/Home/CoffeeCategoryGrid.tsx
  coffect/src/components/Home/CoffeeSuggestBanner.tsx
  coffect/src/components/Home/ProfileFlip.tsx
Labels: 🎨Design
